---
version: "2"
services:
  elasticsearch:
    image: cockcrow/elasticsearch
    ports:
      - "9200:9200"
  kibana:
    build: .
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
...
